services:

  app:
    image: ramadbk-v2_app
    container_name: ramadbk_app
    restart: always
    ports:
      - "80:80"
    environment:
      APP_NAME: RamaDBK
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://0.0.0.0

      LOG_CHANNEL: stderr
      LOG_LEVEL: warning

      DB_CONNECTION: mysql
      DB_HOST: 10.0.1.10
      DB_PORT: 3306
      DB_DATABASE: rama
      DB_USERNAME: admin
      DB_PASSWORD: "Hsr/DY9!1Te#"

      CACHE_STORE: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis

      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""

    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: ramadbk_redis
    restart: always
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
