<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('shipping_inventory_23082021', function (Blueprint $table) {
            $table->integer('s_no');
            $table->integer('stock_no');
            $table->string('stock_number', 12);
            $table->string('chassis_no', 16);
            $table->string('invoice_no', 50);
            $table->integer('shipping_status');
            $table->string('shipping_status_value', 30);
            $table->string('shipping_line', 255);
            $table->string('vessel_name', 255);
            $table->string('voyage_number', 50);
            $table->date('ETD_date');
            $table->date('ETA_date');
            $table->text('Remark_inner_cargo');
            $table->text('Remark_internal_mng');
            $table->date('cancel_date');
            $table->text('cancel_reason');
            $table->boolean('is_authorized');
            $table->text('autherize_remark');
            $table->boolean('shipment_type')->default(2)->comment('shipment type 0 for ro-ro ; 1 for container');
            $table->text('shipment_remark');
            $table->date('bill_of_lading_date');
            $table->string('bill_of_lading_number', 50);
            $table->integer('bill_of_lading_charge');
            $table->date('auth_timestamp');
            $table->timestamp('shipping_remark_last_modified_time')->nullable();
            $table->timestamp('shipping_remark_create_time')->nullable();
            $table->string('BL_sent', 255)->default('0');
            $table->string('BL_received', 255)->default('0');
            $table->date('bill_sent_date');
            $table->string('amount_due', 255)->default('0');
            $table->date('re_shipped_date')->comment('re-shipped date');
            $table->text('re_shipped_remark')->nullable()->comment('re-shipped remark');
            $table->string('BL_new_sent', 255)->default('0');
            $table->date('invoice_date');
            $table->integer('person_in_charge');
            $table->string('person_in_charge_name', 50);
            $table->boolean('is_domestic')->comment('1 - domestic 2 - overseas');
            $table->boolean('status')->default(0)->comment('0-pending, 1-mature, 3-cancelled');
            $table->string('booking_ref', 15);
            $table->string('our_ref', 15);
            $table->date('cut_date');
            $table->integer('forwarder');
            $table->string('forwarder_name', 50);
            $table->text('remark');
            $table->date('request_date');
            $table->string('voyage_no', 30);
            $table->smallInteger('request_status')->comment('in-process =');
            $table->date('applied_date');
            $table->date('inspection_date');
            $table->tinyInteger('inspection_type_id');
            $table->string('ref_no', 20);
            $table->string('fname', 50);
            $table->integer('port_to_id');
            $table->string('port_to', 30);
            $table->string('to_country', 255);
            $table->integer('to_country_id');
            $table->string('lc_bank', 255);
            $table->double('freight_charges');
            $table->double('received_amount');
            $table->double('auction_charge');
            $table->double('custom_clearaence');
            $table->double('fwt_charge');
            $table->double('inspection_charge');
            $table->double('other_charge');
            $table->double('transportation_fee');
            $table->string('_freight', 15);
            $table->date('sailing_date');
            $table->tinyInteger('SO_status')->comment('shipping order status : 1:in process, 2:cancelled, 3:shipped');
            $table->string('auction_name', 100);
            $table->string('ext_color', 15);
            $table->integer('length');
            $table->integer('width');
            $table->integer('height');
            $table->float('m3');
            $table->string('make', 50);
            $table->integer('weight');
            $table->integer('yard_id');
            $table->string('yard_id_value', 250);
            $table->integer('mfg_year');
            $table->string('maker', 50);
            $table->string('type', 50);
            $table->string('subtype', 50);
            $table->boolean('is_updated')->default(2);
            $table->integer('member_id');
            $table->string('autherize_status', 30);
            $table->string('inspection_type_name', 250);
            $table->string('veh_status', 30);
            $table->date('purchase_date');
            $table->string('requested_reason', 30);
            $table->date('courier_date');
            $table->string('docate_no', 250);
            $table->string('courier_remark', 250);
            $table->integer('cc_id');
            $table->string('courier_company_name', 250);
            $table->string('invoice_curr', 10);
            $table->integer('jpy_ex_rate');
            $table->double('total');
            $table->double('payment_allocated');
            $table->tinyInteger('inspection_status');
            $table->date('certificate_issued_date');
            $table->boolean('display');
            $table->integer('requested_by_id');
            $table->string('requested_by', 100);
            $table->string('transport_company', 100);
            $table->date('yard_date');
            $table->date('masho_application_date');
            $table->integer('from_port_id');
            $table->string('from_port', 100);
            $table->integer('from_country_id');
            $table->string('from_country', 100);
            $table->date('expire_date');
            $table->date('issue_date');
            $table->date('latest_date_shipment');
            $table->text('memo');
            $table->date('yard_in_status');
            $table->date('ask_inspection');
            $table->date('ask_tentative_booking');
            $table->date('make_shipping_order');
            $table->date('mark_as_shipped');
            $table->date('actual_etd');
            $table->date('actual_eta');
            $table->string('case_no', 100);
            $table->string('booking_order', 100);
            $table->integer('yard_photo_count');
            $table->text('uploaded_docs');
            $table->boolean('is_inspection_asked')->default(2);
            $table->date('export_masho_uploaded_date');
            $table->boolean('is_repair')->default(2);
            $table->string('repair_no', 15);
            $table->date('request_by');
            $table->date('end_by');
            $table->string('location', 50);
            $table->string('repair_remark', 250);
            $table->double('estimate_cost');
            $table->double('actual_cost');
            $table->string('vendor', 50);
            $table->integer('vendor_id');
            $table->string('repair_status', 50);
            $table->string('repair_invoice_no', 20);
            $table->double('consumption_tax');
            $table->date('repair_invoice_date');
            $table->string('upzipfile', 100);
            $table->boolean('send_to_ship_pending')->default(2);
            $table->boolean('copy_to_inspection')->default(2);
            $table->string('hs_code', 20);
            $table->boolean('send_to_si')->default(2);
            $table->double('auction_transportation_cost');
            $table->double('inspection_charges_cost');
            $table->double('auction_fee_cost');
            $table->double('road_tax_cost');
            $table->double('recycle_fee_cost');
            $table->double('auction_listing_fee_cost');
            $table->double('other_charges_cost');
            $table->double('inland_transportation_cost');
            $table->double('repair_charges_cost');
            $table->double('fwt_charges_cost');
            $table->double('spare_parts_cost');
            $table->double('freight_charges_cost');
            $table->double('shipping_charges_cost');
            $table->double('vanning_charges_cost');
            $table->double('operating_cost');
            $table->double('insurance_cost');
            $table->double('dismantle_charges_cost');
            $table->double('consumption_tax_cost');
            $table->double('brokers_commision_cost');
            $table->double('claim_refund_cost');
            $table->double('storage_fee_cost');
            $table->double('domestic_transport_fee_cost');
            $table->double('amendment_charge_cost');
            $table->double('photo_cost');
            $table->double('lashing_cost');
            $table->double('go_down_cost');
            $table->double('washing_cost');
            $table->double('radiation_inspection_cost');
            $table->double('bank_charges_cost');
            $table->double('bl_bank_acceptance_fee_cost');
            $table->double('engine_check_charges_cost');
            $table->date('bl_issue_date');
            $table->string('bl_status', 50);
            $table->string('bl_collector', 50);
            $table->string('bl_remark', 250);
            $table->string('inspection_result', 20);
            $table->string('inspection_remarks', 250);
            $table->string('lc_number', 100);
            $table->integer('repair_invoice_created_by');
            $table->string('repair_invoice_created_by_id', 50);
            $table->dateTime('repair_invoice_created_on');
            $table->date('mail_send_date');
            $table->date('inspection_mail_send_date');
            $table->date('si_mail_send_date');
            $table->date('booking_mail_send_date');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('shipping_inventory_23082021');
    }
};
