<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('vehicle_details_aucnet', function (Blueprint $table) {
            $table->integer('stock_no')->unsigned();
            $table->integer('user_profile_id');
            $table->string('stock_number', 25)->nullable();
            $table->double('default_price');
            $table->double('price')->nullable();
            $table->date('price_update_date');
            $table->double('actual_price');
            $table->double('commission');
            $table->double('buying_price')->nullable();
            $table->string('consumption_tax', 50)->nullable();
            $table->integer('status')->unsigned()->default(0);
            $table->boolean('display')->nullable()->default(1);
            $table->integer('location_id')->unsigned()->nullable();
            $table->string('location', 100)->nullable();
            $table->integer('port_id')->unsigned()->nullable();
            $table->string('port', 100)->nullable();
            $table->boolean('new_used')->nullable()->comment('0-used 1-new');
            $table->integer('yard_id')->unsigned()->nullable();
            $table->integer('type_id')->unsigned()->nullable();
            $table->integer('subtype_id')->unsigned()->nullable();
            $table->integer('make_id')->unsigned()->nullable();
            $table->integer('maker_id')->unsigned()->nullable();
            $table->integer('model_id')->unsigned()->nullable();
            $table->string('type', 25)->nullable();
            $table->string('subtype', 50)->nullable();
            $table->string('make', 50)->nullable();
            $table->string('maker', 50)->nullable();
            $table->string('model', 50)->nullable();
            $table->string('grade', 50)->nullable();
            $table->integer('mfg_year')->nullable();
            $table->integer('mfg_month')->nullable();
            $table->string('chassis_no', 50)->nullable();
            $table->integer('mileage')->nullable();
            $table->integer('engine_cc')->unsigned()->nullable();
            $table->string('drive', 25)->nullable();
            $table->char('grade_ext', 3)->nullable()->default('');
            $table->char('grade_int', 3)->nullable()->default('');
            $table->char('auction_grade', 3)->nullable()->default('');
            $table->string('doors', 25)->nullable();
            $table->string('seat_capacity', 25)->nullable();
            $table->string('fuel', 50)->nullable();
            $table->string('transmission', 50)->nullable();
            $table->string('model_code', 20);
            $table->integer('length')->nullable();
            $table->integer('width')->nullable();
            $table->integer('height')->nullable();
            $table->integer('weight')->nullable();
            $table->double('m3');
            $table->date('purchase_date')->nullable();
            $table->date('extend_date');
            $table->integer('supplier_id')->nullable();
            $table->integer('spare_supplier_id');
            $table->integer('purchased_by')->nullable();
            $table->integer('requested_by');
            $table->boolean('requested_reason')->comment('1 - stock basis, 2 - requested');
            $table->boolean('show_auc')->nullable();
            $table->dateTime('create_date')->nullable();
            $table->dateTime('update_date')->nullable();
            $table->string('int_color', 15)->nullable()->default('');
            $table->string('ext_color', 15)->nullable()->default('');
            $table->char('wd', 3)->nullable()->default('0');
            $table->text('other_option')->nullable();
            $table->dateTime('start_date')->nullable();
            $table->dateTime('close_date')->nullable();
            $table->string('data_source', 25)->nullable();
            $table->dateTime('confirm_time')->nullable();
            $table->string('data_sites', 200)->nullable()->default('');
            $table->string('veh_title', 255)->nullable()->default('');
            $table->boolean('accident')->nullable()->default(0);
            $table->string('vin_number', 100)->nullable()->default('');
            $table->string('ext_info_pos', 255)->nullable()->default('');
            $table->string('ext_info_pos_2', 250)->comment('accessories for good point');
            $table->string('ext_info_neg', 255)->nullable()->default('');
            $table->string('sellArea', 255)->nullable()->default('');
            $table->boolean('is_tcv')->nullable()->default(0);
            $table->string('export_area_id', 255)->nullable()->default('');
            $table->string('dead_stock', 255)->default('0');
            $table->string('is_spare', 255)->default('0');
            $table->boolean('watch_list_status')->comment('1 - yes 2 - no');
            $table->double('market_price')->comment('in yen');
            $table->date('market_price_date');
            $table->integer('customer_id')->comment('when we choose status ');
            $table->string('engine_type', 150);
            $table->text('model_description');
            $table->text('engine_description');
            $table->integer('transport_comp_id');
            $table->boolean('cost_type_status')->default(2)->comment('1-have cost type, 2 - not have');
            $table->string('videoFor', 50);
            $table->string('youtube_url', 200);
            $table->boolean('is_auction')->default(2);
            $table->string('auction_system', 15);
            $table->string('lot_no', 15);
            $table->string('hall_name', 50);
            $table->string('hall_location', 50);
            $table->dateTime('input_date');
            $table->boolean('jays_lk')->default(2);
            $table->double('total_price');
            $table->double('price_jpy');
            $table->integer('quantity')->default(1);
            $table->integer('currency');
            $table->string('part_number', 50);
            $table->text('description');
            $table->text('keyword_tag');
            $table->integer('main_category_id');
            $table->integer('sub_category_id');
            $table->smallInteger('sort_order')->default(10);
            $table->boolean('sold_shipped_30')->default(2);
            $table->string('auction_name', 100);
            $table->double('auction_charge');
            $table->boolean('is_green_paper')->default(2);
            $table->string('purchased_by_value', 250);
            $table->string('requested_by_value', 250);
            $table->string('yard_id_value', 250);
            $table->boolean('is_completed')->default(1);
            $table->string('country', 200);
            $table->double('special_price');
            $table->date('yard_date');
            $table->integer('transport_company_id');
            $table->string('transport_company', 100);
            $table->string('remarks', 250);
            $table->string('auction', 100);
            $table->string('bid_number', 100);
            $table->date('auction_date');
            $table->boolean('auc_import')->default(0);
            $table->boolean('img_copy')->default(2);
            $table->integer('hit_counter');
            $table->string('pics', 100);
            $table->string('auc_pics', 100);
            $table->integer('enquiry_counter');
            $table->string('customer_name', 50);
            $table->boolean('is_import')->default(2);
            $table->boolean('mail_sent')->default(2);
            $table->date('checked_date')->comment('date to check if mail sent for country vise ');
            $table->integer('yard_photo_count');
            $table->text('uploaded_docs');
            $table->boolean('is_updated')->default(2);
            $table->boolean('check_spare_key')->default(2);
            $table->boolean('check_sd_card')->default(2);
            $table->boolean('remove_hard_copy')->default(2);
            $table->string('transport_comment', 250);
            $table->boolean('re_auction')->default(2);
            $table->boolean('gp_mail_sent')->default(2);
            $table->dateTime('gp_sent_date');
            $table->boolean('is_repair')->default(2);
            $table->boolean('is_repair_invoice')->default(2);
            $table->integer('create_by');
            $table->string('create_by_name', 30);
            $table->integer('update_by');
            $table->string('update_by_name', 30);
            $table->integer('agasta_stock_no');
            $table->string('agasta_stock_img', 250);
            $table->boolean('to_be_delete')->default(2);
            $table->double('agasta_commission');
            $table->double('agasta_price');
            $table->string('office', 30);
            $table->text('ass_ids');
            $table->text('ass_vals');
            $table->string('d_stock_number', 50);
            $table->string('dealer_ref_no', 50);
            $table->integer('d_stock_no');
            $table->string('sync_as', 10);
            $table->integer('reg_year');
            $table->integer('reg_month');
            $table->boolean('customer_canceled')->default(2);
            $table->integer('production_year');
            $table->integer('production_month');
            $table->date('shaken_date');
            $table->boolean('send_to_recycle')->default(2);
            $table->date('autotax_date_of_apply');
            $table->tinyInteger('autotax_apply')->nullable()->default(2);
            $table->integer('autotax_refund_amt');
            $table->date('autotax_rcv_date');
            $table->tinyInteger('autotax_completed')->nullable()->default(2);
            $table->date('insurance_date_of_apply');
            $table->tinyInteger('insurance_apply')->nullable()->default(2);
            $table->tinyInteger('liability_insurance')->nullable()->default(2);
            $table->date('date_of_entry');
            $table->integer('numbers_of_months_remaining');
            $table->date('date_of_expiry');
            $table->integer('insurance_refund_amt');
            $table->date('insurance_rcv_date');
            $table->tinyInteger('insurance_completed')->nullable()->default(2);
            $table->date('radiation_date_of_apply');
            $table->tinyInteger('radiation_apply')->nullable()->default(2);
            $table->integer('radiation_refund_amt');
            $table->date('radiation_rcv_date');
            $table->tinyInteger('radiation_completed')->nullable()->default(2);
            $table->tinyInteger('non_radiation')->nullable()->default(2);
            $table->boolean('bando_stock')->default(2);
            $table->tinyInteger('autotax_fax_auction')->default(2);
            $table->tinyInteger('autotax_application_poa')->default(2);
            $table->tinyInteger('autotax_certificate_seal')->default(2);
            $table->tinyInteger('cert_autotax_payment')->default(2);
            $table->string('radiation_insu_no', 20);
            $table->string('radiation_insu_company', 1000);
            $table->string('radiation_insu_reg_no', 30);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('vehicle_details_aucnet');
    }
};
